name: Github Jest Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash -1 {0}
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Jest
        run: npm install --save-dev jest

      - name: Run Jest tests
        run: npm test
