name: Github Jest Tests
run-name: ${{ github.actor }} is Jest tests
on: [push]
jobs:
  unit-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: "20"
      - name: Install dependencies
        run: npm install 
      - run: npm install --save-dev babel-jest @babel/core @babel/preset-env
      - run: npm install --save-dev @babel/preset-typescript
      - run: npm install --save-dev @types/jest
      - run: npm install jest --save-dev

      - name: Run Jest tests
        run: npm run test
